#### Pandas-Dataframe And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [2]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("series \n",series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
## Create a series from dictionary
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
## Dataframe
## create  a Dataframe from a dictionary of list

data={
    'Name':['Arnav','John','Jack'],
    'Age':[19,30,45],
    'city':['Indore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      city
0  Arnav   19    Indore
1   John   30  New York
2   Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [6]:
import numpy as np

np.array(df)

array([['Arnav', 19, 'Indore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [21]:
# Create a Data frame From a List of Dictionaries

data = [
    {'Name': 'Arnav', 'Age': '19', 'City': 'Indore'},
    {'Name': 'John', 'Age': 34, 'City': 'Bangalore'},
    {'Name': 'Bappy', 'Age': 32, 'City': 'Bangalore'},
    {'Name': 'Jack', 'Age': 32, 'City': 'Bangalore'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name Age       City
0  Arnav  19     Indore
1   John  34  Bangalore
2  Bappy  32  Bangalore
3   Jack  32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [8]:
df = pd.read_csv('Orders.csv')
df.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [9]:
df.tail()

    Order ID  Order Date CustomerName             State     City
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

In [10]:
df

    Order ID  Order Date CustomerName             State     City
0    B-26055  10-03-2018    Harivansh     Uttar Pradesh  Mathura
1    B-25993  03-02-2018       Madhav             Delhi    Delhi
2    B-25973  24-01-2018  Madan Mohan     Uttar Pradesh  Mathura
3    B-25923  27-12-2018        Gopal       Maharashtra   Mumbai
4    B-25757  21-08-2018     Vishakha    Madhya Pradesh   Indore
..       ...         ...          ...               ...      ...
495  B-25742  03-08-2018       Ashwin               Goa      Goa
496  B-26088  26-03-2018       Bhavna            Sikkim  Gangtok
497  B-25707  01-07-2018      Shivani       Maharashtra   Mumbai
498  B-25758  22-08-2018      Shubham  Himachal Pradesh    Simla
499  B-26095  28-03-2018      Monisha         Rajasthan   Jaipur

[500 rows x 5 columns]

In [22]:
### Accessing Data from Dataframe
df['Name']

0    Arnav
1     John
2    Bappy
3     Jack
Name: Name, dtype: object

In [18]:
df.loc[0][0]

C:\Users\ARNAV MAHAJAN\AppData\Local\Temp\ipykernel_22320\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'B-26055'

In [17]:
df.iloc[0][2]

C:\Users\ARNAV MAHAJAN\AppData\Local\Temp\ipykernel_22320\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Harivansh'

In [23]:
df

    Name Age       City
0  Arnav  19     Indore
1   John  34  Bangalore
2  Bappy  32  Bangalore
3   Jack  32  Bangalore

In [24]:
### Accessing a Specified element
df.at[2,"Name"]

'Bappy'

In [25]:
## Accessing a specified element using int
df.iat[2,2]

'Bangalore'

In [26]:
df

    Name Age       City
0  Arnav  19     Indore
1   John  34  Bangalore
2  Bappy  32  Bangalore
3   Jack  32  Bangalore

In [27]:
### data manipulation with dataframe
df

    Name Age       City
0  Arnav  19     Indore
1   John  34  Bangalore
2  Bappy  32  Bangalore
3   Jack  32  Bangalore

In [29]:
## Adding a column
df['Salary'] = [50000,60000,70000,80000]
df

    Name Age       City  Salary
0  Arnav  19     Indore   50000
1   John  34  Bangalore   60000
2  Bappy  32  Bangalore   70000
3   Jack  32  Bangalore   80000

In [35]:
## Remove a column
df.drop('Salary',axis= 1,inplace=True)

In [36]:
df

    Name Age       City
0  Arnav  19     Indore
1   John  34  Bangalore
2  Bappy  32  Bangalore
3   Jack  32  Bangalore

In [42]:
## add age to the column
df['Age'] = df['Age'].astype(int) + 1
df

    Name  Age       City
0  Arnav   20     Indore
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   Jack   33  Bangalore

In [43]:
df.drop(0,inplace=True)

In [44]:
df

    Name  Age       City
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   Jack   33  Bangalore

In [45]:
df = pd.read_csv('Orders.csv')
df.head(5)

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [47]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Order ID        object
Order Date      object
CustomerName    object
State           object
City            object
dtype: object
Statistical summary:
        Order ID  Order Date CustomerName        State    City
count       500         500          500          500     500
unique      500         307          336           19      25
top     B-26055  24-11-2018       Shreya  Maharashtra  Indore
freq          1           7            6           94      71

In [48]:
df.describe()

       Order ID  Order Date CustomerName        State    City
count       500         500          500          500     500
unique      500         307          336           19      25
top     B-26055  24-11-2018       Shreya  Maharashtra  Indore
freq          1           7            6           94      71