# Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

## Nominal/OHE Encoding

One-hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms.

In this technique, each category is represented as a binary vector where each bit corresponds to a unique category.

For example, if we have a categorical variable **"color"** with three possible values (**red, green, blue**), we can represent it using one-hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [20]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [21]:
## create a simple dataframe
df = pd.DataFrame({
    'color':['red','green','orange','blue','black']
})

In [22]:
df.head()

    color
0     red
1   green
2  orange
3    blue
4   black

In [23]:
##create an instance of onehotencoder
encoder = OneHotEncoder()

In [24]:
## perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [25]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [26]:
encoder_df

   color_black  color_blue  color_green  color_orange  color_red
0          0.0         0.0          0.0           0.0        1.0
1          0.0         0.0          1.0           0.0        0.0
2          0.0         0.0          0.0           1.0        0.0
3          0.0         1.0          0.0           0.0        0.0
4          1.0         0.0          0.0           0.0        0.0

In [27]:
#for new data
encoder.transform([['blue']]).toarray()

C:\Users\ARNAV MAHAJAN\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 0., 0., 0.]])

In [28]:
pd.concat([df,encoder_df],axis = 1)

    color  color_black  color_blue  color_green  color_orange  color_red
0     red          0.0         0.0          0.0           0.0        1.0
1   green          0.0         0.0          1.0           0.0        0.0
2  orange          0.0         0.0          0.0           1.0        0.0
3    blue          0.0         1.0          0.0           0.0        0.0
4   black          1.0         0.0          0.0           0.0        0.0

In [29]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [37]:
df1 = sns.load_dataset('tips')

In [38]:
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
nominal = OneHotEncoder()

In [43]:
encoder = nominal.fit_transform(df1[['total_bill','tip','sex','smoker','day','time','size']]).toarray()

In [45]:
encoder_df = pd.DataFrame(encoder,columns=nominal.get_feature_names_out())

In [46]:
encoder_df

,total_bill_3.07,total_bill_5.75,total_bill_7.25,total_bill_7.51,total_bill_7.56,total_bill_7.74,total_bill_8.35,total_bill_8.51,total_bill_8.52,total_bill_8.58,...,day_Sun,day_Thur,time_Dinner,time_Lunch,size_1,size_2,size_3,size_4,size_5,size_6
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
240,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
241,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
243,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [48]:
pd.concat([df1,encoder_df],axis = 1)

,total_bill,tip,sex,smoker,day,time,size,total_bill_3.07,total_bill_5.75,total_bill_7.25,...,day_Sun,day_Thur,time_Dinner,time_Lunch,size_1,size_2,size_3,size_4,size_5,size_6
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
243,18.78,3.00,Female,No,Thur,Dinner,2,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

# Label Encoding

Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories.

For example, if we have a categorical variable **"color"** with three possible values (**red, green, blue**), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'color':['red','green','orange','blue','black']
})

In [4]:
df.head()

    color
0     red
1   green
2  orange
3    blue
4   black

In [9]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [10]:
lbl_encoder.fit_transform(df[['color']])

C:\Users\ARNAV MAHAJAN\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([4, 2, 3, 1, 0])

In [11]:
lbl_encoder.transform([['red']])

C:\Users\ARNAV MAHAJAN\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([4])

In [12]:
lbl_encoder.transform([['black']])

C:\Users\ARNAV MAHAJAN\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

## Ordinal Encoding

Ordinal encoding is used to encode categorical data that has an intrinsic order or ranking.

In this technique, each category is assigned a numerical value based on its position in the order.

For example, if we have a categorical variable **"education level"** with four possible values (**high school, college, graduate, post-graduate**), we can represent it using ordinal encoding as follows:

1. High School: 1
2. College: 2
3. Graduate: 3
4. Post-Graduate: 4

In [15]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [16]:
# create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [17]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [18]:
## create an instance of OrdinalEncoder and then fit_transform
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [19]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [20]:
encoder.transform([['small']])

C:\Users\ARNAV MAHAJAN\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

# Target Guided Ordinal Encoding

It is a technique used to encode categorical variables based on their relationship with the target variable.

This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category.

This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [21]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [22]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [24]:
mean_price = df.groupby('city')['price'].mean()

In [25]:
mean_price

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [26]:
df['city_encoded'] = df['city'].map(mean_price)

In [27]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [31]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [32]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [33]:
df1 = sns.load_dataset('tips')

In [35]:
df1[['total_bill','time']]

     total_bill    time
0         16.99  Dinner
1         10.34  Dinner
2         21.01  Dinner
3         23.68  Dinner
4         24.59  Dinner
..          ...     ...
239       29.03  Dinner
240       27.18  Dinner
241       22.67  Dinner
242       17.82  Dinner
243       18.78  Dinner

[244 rows x 2 columns]

In [ ]:
mean_price2 = df1.groupby('time')['total_bill'].mean()

C:\Users\ARNAV MAHAJAN\AppData\Local\Temp\ipykernel_17748\2528853881.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df1.groupby('time')['total_bill'].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [44]:
df1['time_encoded'] = df1['time'].map(mean_price2)

In [45]:
df1

     total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]

In [47]:
df1[['total_bill','time_encoded']]

     total_bill time_encoded
0         16.99    20.797159
1         10.34    20.797159
2         21.01    20.797159
3         23.68    20.797159
4         24.59    20.797159
..          ...          ...
239       29.03    20.797159
240       27.18    20.797159
241       22.67    20.797159
242       17.82    20.797159
243       18.78    20.797159

[244 rows x 2 columns]